Challenges 4 & 5
DACSS/601_Fall_2022 pull request #221
Opened 2022-10-17 03:49 UTC by amaciaszek

There are some packages used here you may need to install usmap tigris

2022-10-17 16:55 UTC, ThogaruSathvik requested changes
kindly add these challenges to posts folder and submit the pull request again

2022-10-18 23:15 UTC, ThogaruSathvik reviewed
Kindly add your challenges to posts folder and submit the pull request again to submission branch

2022-10-19 02:50 UTC, amaciaszek commented
Did it work now?

On Tue, Oct 18, 2022, 7:16 PM Sathvik Thogaru ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Kindly add your challenges to posts folder and submit the pull request
> again to submission branch
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DACSS/601_Fall_2022/pull/221#pullrequestreview-1146627173>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQDHKWPIRD7IO2HJEMHP763WD4VTVANCNFSM6AAAAAARGVBM7Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-19 17:02 UTC, ThogaruSathvik approved these changes

2022-10-19 17:02 UTC, merged